### ISSUE TITLE
French lang file for gmod

### ISSUE THREAD

**Issue by Scarxix** [matbyte-com/vyhub-gmod#13]
{
"ply": {
"banned": "Le joueur <green>%s</green> a été <red>banni pendant %s</red>. Raison : <green>%s</green>",
"no_permissions": "Vous n'avez pas toutes les permissions requises.",
"banned_self": "Vous êtes banni de ce serveur",
"group_changed": "Votre groupe a été changé en <green>%s</green>.",
"error_get": "Impossible de trouver le joueur. Veuillez réessayer."
},
"warning": {
"user_warned": "<red>%s</red> a été averti par <green>%s</green>. Raison : <green>%s</green>",
"cmd_help": "<red>Joueur invalide !</red> Utilisation : <green>!warn <pseudo> <raison></green>",
"toggled_self": "Le statut d'un de vos avertissements a été modifié. Vérifiez vos avertissements avec !dashboard.",
"create_error": "Erreur lors de l'ajout d'un avertissement pour le joueur <green>%s</green> : <red>%s</red>",
"toggled": "Statut de l'avertissement modifié.",
"deleted": "Avertissement supprimé.",
"deleted_self": "Un de vos avertissements a été supprimé. Vérifiez vos avertissements avec !dashboard.",
"received": "Vous avez reçu un avertissement de la part de <green>%s</green> : <red>%s</red>"
},
"ban": {
"status_changed": "Statut de bannissement de %s modifié avec succès : %s.",
"user_banned": "<red>%s</red> a été banni par <green>%s</green> pendant <red>%s</red>. Raison : <green>%s</green>"
},
"rslots": {
"kick": "Un joueur avec un slot réservé s'est connecté au serveur et vous avez été expulsé pour libérer de la place",
"full": "Le serveur est complet",
"full_no_slot": "Le serveur est complet et vous n'avez pas accès à un slot réservé"
},
"dashboard": {
"select_user": "Veuillez sélectionner un utilisateur.",
"action_ban": "Bannir",
"action_warn": "Avertir"
},
"other": {
"active": "Actif",
"active_global": "Actif (Global)",
"inactive": "Inactif",
"disabled": "Désactivé",
"unbanned": "Débanni",
"id": "ID",
"reason": "Raison",
"dead": "MORT",
"ban_date": "Date de bannissement",
"unban_date": "Date de débannissement",
"unban": "Débannir",
"reban": "Rebannir",
"admin": "Administrateur",
"actions": "Actions",
"never": "Jamais",
"warnings": "Avertissements",
"date": "Date",
"ban": "Bannir",
"warn": "Avertir",
"bans": "Bannissements",
"unknown": "Inconnu",
"minutes": "Minutes",
"x_minutes": "%i minutes",
"permanently": "Définitivement",
"unban_url": "URL de débannissement",
"error_api": "Erreur lors de la communication avec l'API : %s"
}
}

**Comment by ibot3** [comment]
Thanks for you submission.
We just added a french translation with vyhub-gmod 1.4.3.
The translation may slightly differs from yours.

For future translations, please use our translation tool at https://translate.matbyte.com/projects/vyhub/vyhub-lang/.
